# Generated by Django 4.2.1 on 2023-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Book Title')),
                ('author_name', models.CharField(max_length=255, verbose_name='Author Name')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
